[font]
normal = { family = "Mononoki Nerd Font", style = "Regular" }
bold = { family = "Mononoki Nerd Font", style = "Bold" }
italic = { family = "Mononoki Nerd Font", style = "Italic" }
size = 20.0

[window]
decorations = "none"
opacity = 1.0

[colors]
# GitHub Dark Default

# Default colors
[colors.primary]
background = "#2E3440"
foreground = "#D8DEE9"

# Normal colors
[colors.normal]
black   = "#3B4252"
red     = "#BF616A"
green   = "#A3BE8C"
yellow  = "#EBCB8B"
blue    = "#81A1C1"
magenta = "#B48EAD"
cyan    = "#88C0D0"
white   = "#E5E9F0"

# Bright colors
[colors.bright]
black   = "#4C566A"
red     = "#BF616A"
green   = "#A3BE8C"
yellow  = "#EBCB8B"
blue    = "#81A1C1"
magenta = "#B48EAD"
cyan    = "#8FBCBB"
white   = "#ECEFF4"

# Cursor colors
[colors.cursor]
text   = "#2E3440"
cursor = "#D8DEE9"

# Selection colors
[colors.selection]
text       = "CellForeground"
background = "#4C566A"

# Search colors
[colors.search]
[colors.search.matches]
foreground = "#0d1117"
background = "#e3b341"

[colors.search.focused_match]
foreground = "#0d1117"
background = "#58a6ff"

# Hints colors
[colors.hints]
[colors.hints.start]
foreground = "#0d1117"
background = "#e3b341"

[colors.hints.end]
foreground = "#0d1117"
background = "#58a6ff"
