#!/bin/sh

#xautolock
exec xautolock -time 60 -locker slock &

#slstatus
exec slstatus &

# qt6ct
export QT_QPA_PLATFORMTHEME=qt6ct

#java-dwm
export _JAVA_AWT_WM_NONREPARENTING=1
export AWT_TOOLKIT=MToolkit

# xcompmgr
exec xcompmgr &

#nitrogen 
exec nitrogen --restore &

#xfce-power-manager
exec /usr/bin/xfce4-power-manager &

#polkit
#exec /usr/lib/polkit-1 &

#dunst
exec dunst &

#monitors
exec /home/crahantan/code/dotfiles_dwm/dwm/scripts/monitors &

#dwm reload
while true; do
  # Log stderror to a file
  dwm 2>~/.dwm.log
  # No error logging
  #dwm >/dev/null 2>&1
done
