#!/bin/sh

#xautolock
exec xautolock -time 60 -locker slock &

#slstatus
exec slstatus &

# qt gtk2
export QT_QPA_PLATFORMTHEME=gtk2

#java-dwm
export _JAVA_AWT_WM_NONREPARENTING=1
export AWT_TOOLKIT=MToolkit

#xcompmgr
exec xcompmgr &

#nitrogen 
exec nitrogen --restore &

#xfce-power-manager
exec xfce4-power-manager &

#dunst
exec dunst &

#dwm reload
while true; do
  # Log stderror to a file
  dwm 2>~/.dwm.log
  # No error logging
  #dwm >/dev/null 2>&1
done
