#!/bin/sh

#xautolock
exec xautolock -time 60 -locker slock &

#slstatus
exec slstatus &

# qt gtk2
export QT_QPA_PLATFORMTHEME=gtk2

#java-dwm
export _JAVA_AWT_WM_NONREPARENTING=1
export AWT_TOOLKIT=MToolkit	

#monitors
exec $HOME/.config/suckless/scripts/monitors &

#nitrogen 
exec nitrogen --restore &

#xfce-power-manager
exec xfce4-power-manager &

#xcompmgr
#exec xcompmgr -n -c -t-5 -l-5 -r4.2 -o.55 &

#dunst
exec dunst &

#dwm reload
while true; do
  # Log stderror to a file
  dwm 2>~/.dwm.log
  # No error logging
  #dwm >/dev/null 2>&1
done
