#!/bin/sh

userresources=$HOME/.Xresources

#timezone
exec timedatectl set-timezone America/Mexico_City &

#xcompmgr
exec xcompmgr &

#xautolock
exec xautolock -time 60 -locker slock &

#slstatus
exec slstatus &

#PATHS && exports
export JAVA_HOME="/usr/lib/jvm/java-22-jdk"
export PATH=$HOME/.local/bin:$HOME/.local/bin/scripts:$JAVA_HOME/bin:$PATH
export QT_QPA_PLATFORMTHEME=gtk2
#java-dwm
export _JAVA_AWT_WM_NONREPARENTING=1
export AWT_TOOLKIT=MToolkit

#wal
exec $HOME/.local/bin/wal -R &

#xfce-power-manager
exec /usr/bin/xfce4-power-manager &

#xfce-polkit
exec /usr/lib/xfce-polkit/xfce-polkit &

#xrdb Xresources
exec xrdb -merge $HOME/.Xresources &

#xrandr
intern=eDP1
extern=HDMI-0
extern_lg=DP-1

if xrandr | grep "$extern disconnected"; then
	xrandr --output "$extern" --off --output "$extern_lg" --off --output "$intern" --auto
else
	xrandr --output "$intern" --off --output "$extern" --mode 1920x1080 --rate 60 --output "$extern_lg" --mode 1920x1080 --rate 60 --right-of "$extern"
fi

#dwm
while true; do
    # Log stderror to a file 
    dwm 2> ~/.dwm.log
    # No error logging
    #dwm >/dev/null 2>&1
done
