## Theme
include ./theme.conf

## Fuente
font_family     JetBrainsMono Nerd Font 
bold_font       auto
italic_font     auto 
font_size 10.0

background_opacity 0.75
background_blur 10 
dynamic_background_opacity yes
remember_window_size  yes
initial_window_width  640
initial_window_height 400
remember_window_position yes
