## Fuente
font_family      Mononoki Nerd Font
bold_font        Mononoki Nerd Font Bold
italic_font      Mononoki Nerd Font Italic
font_size 14.0

## Nord theme
include ./kanagawa/kanagawa.conf

## Ventana
hide_window_decorations no
background_opacity 0.90
background_blur 100

## Colores del tema GitHub Dark Default
## Colores predeterminados
# foreground #c9d1d9
# background #0d1117

## Colores normales
# color0 #484f58
# color1 #ff7b72
# color2 #3fb950
# color3 #d29922
# color4 #58a6ff
# color5 #bc8cff
# color6 #39c5cf
# color7 #b1bac4

## Colores brillantes
# color8  #6e7681
# color9  #ffa198
# color10 #56d364
# color11 #e3b341
# color12 #79c0ff
# color13 #d2a8ff
# color14 #56d4dd
# color15 #f0f6fc

## Colores del cursor
# cursor #c9d1d9
# cursor_text_color #0d1117

## Colores de selección
# selection_foreground #0d1117
# selection_background #264f78

## Colores de URL
# url_color #58a6ff
