#!/bin/sh

# Iniciar servicios de D-Bus para aplicaciones de Xfce
if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS"; then
    eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi

#xautolock
exec /usr/bin/xautolock -time 60 -locker slock &

#slstatus
exec /usr/local/bin/slstatus &

#java-dwm
export _JAVA_AWT_WM_NONREPARENTING=1
export AWT_TOOLKIT=MToolkit	

#powermanagement
exec /usr/bin/xfce4-power-manager &

# Iniciar el Gestor de Ajustes de Xfce (xfsettingsd)
# Esto se encarga de la configuración del teclado, temas, etc.
exec /usr/bin/xfsettingsd &

#xfce4-screensaver
exec /usr/bin/xfce4-screensaver &

#nitrogen 
exec /usr/bin/nitrogen --restore &

#picom
exec /usr/bin/picom &

#dunst
exec /usr/bin/dunst &
exec /usr/bin/mpris-notifier &

#dwm reload
while true; do
  # Log stderror to a file
  dwm 2>~/.dwm.log
  # No error logging
  #dwm >/dev/null 2>&1
done
