#!/bin/bash

# Verifica si HDMI-1-2 está conectado
if xrandr | grep "HDMI-1-2 connected"; then
    # Activa HDMI-1-2
    xrandr --output HDMI-1-2 --mode 1920x1080 --rate 60 
    # Si HDMI-1-2 está conectado, pon el monitor interno a la derecha
    xrandr --output eDP-1 --mode 1920x1080 --rate 60 --prymary --right-of HDMI-1-2
else
    # Si HDMI-1-2 no está conectado, enciende el monitor interno eDP-1
    xrandr --output eDP-1 --mode 1920x1080 --rate 60 --primary
fi

# Salida exitosa
echo "Configuración de monitores completada."

