#!/bin/bash

# Pamixer Increase
exec pamixer -i 5 & 

# Get current volume level
VOLUME=$(amixer get Master | grep 'Front Left' | awk -F'[][]' '{ print $2 }' | sed 's/%//')


# Display notification using dunst
dunstify -u normal "Volume: ${VOLUME}%"
