#!/bin/bash

# Verifica si HDMI-1-0 está conectado
if xrandr | grep "HDMI-1-0 connected"; then
    # Si HDMI-1-0 está conectado, apaga el monitor interno eDP-1
    xrandr --output eDP-1 --off
    # Activa HDMI-1-0
    xrandr --output HDMI-1-0 --auto
else
    # Si HDMI-1-0 no está conectado, enciende el monitor interno eDP-1
    xrandr --output eDP-1 --auto
    # Apaga HDMI-1-0 si está conectado
    xrandr --output HDMI-1-0 --off
fi

# Salida exitosa
echo "Configuración de monitores completada."

